#!/usr/bin/env bash
# build-bundle.sh — Regenerate the Perplexity / Comet review bundle.
#
# Concatenates every git-tracked text file in the repo into a single
# markdown document. Skips binaries (images, fonts, archives) and the
# bundle output itself. Includes the working-tree content, so uncommitted
# changes are captured.
#
# Output:
#   tmp/perplexity-bundle.md  (project, gitignored)
#   ~/Downloads/perplexity-bundle.md  (for upload to Comet / Perplexity)
#   ~/Desktop/perplexity-bundle.md    (backup)
#
# Usage:
#   bash scripts/build-bundle.sh
#   npm run bundle
#
# The bundle is large (~3 MB / ~40k lines). Comet and Perplexity Pro
# both accept it as a single .md upload. Drop into the chat, then paste
# the standard review prompt.

set -euo pipefail

# Anchor to repo root regardless of cwd
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
cd "${REPO_ROOT}"

OUT="tmp/perplexity-bundle.md"
mkdir -p tmp

VERSION=$(python3 -c "import json; print(json.load(open('src/data/meta.json'))['version'])")
LAST_UPDATED=$(python3 -c "import json; print(json.load(open('src/data/meta.json'))['lastUpdated'])")
GEN_DATE=$(date '+%Y-%m-%d %H:%M %Z')

# Get git short hash and dirty status for transparency
GIT_REF=$(git rev-parse --short HEAD 2>/dev/null || echo "no-git")
GIT_DIRTY=""
if ! git diff-index --quiet HEAD -- 2>/dev/null; then
  GIT_DIRTY=" (working tree has uncommitted changes — bundle reflects working tree, not HEAD)"
fi

# File-type extensions to skip (binaries, derived)
SKIP_EXT_REGEX='\.(png|jpg|jpeg|gif|ico|pdf|zip|woff|woff2|ttf|otf|eot|svg)$'
# Files to explicitly skip (auto-generated, recursive, lock files)
SKIP_FILE_REGEX='^(public/visitor-count\.json|public/rss\.xml|tmp/perplexity-bundle\.md|package-lock\.json)$'

# Build the bundle
{
  echo '# CANADA UNDER CARNEY — FULL REPO BUNDLE'
  echo
  echo "Generated: ${GEN_DATE}"
  echo "Dashboard version: ${VERSION}"
  echo "meta.json lastUpdated: ${LAST_UPDATED}"
  echo "Git ref: ${GIT_REF}${GIT_DIRTY}"
  echo 'Live URL: https://sawatter.github.io/canada-under-carney/'
  echo 'Repo: https://github.com/Sawatter/canada-under-carney'
  echo
  echo 'This bundle is the verbatim content of every git-tracked text file'
  echo 'in the repository. Treat it as the authoritative source for review.'
  echo 'Binary files (images, fonts, SVG icons) and auto-generated files'
  echo '(visitor count, RSS feed, lock files) are excluded.'
  echo
  echo '---'
  echo
  echo '# TABLE OF CONTENTS'
  echo
  git ls-files \
    | grep -v -E "${SKIP_EXT_REGEX}" \
    | grep -v -E "${SKIP_FILE_REGEX}" \
    | sort \
    | awk '{print "- " $0}'
  echo
  echo '---'
  echo

  # Concatenate each file with a clear header and a code fence
  TOTAL=0
  while IFS= read -r f; do
    [ -f "$f" ] || continue
    TOTAL=$((TOTAL + 1))
    echo
    echo "## FILE: ${f}"
    echo
    # Pick a code fence language from extension for syntax hinting
    case "${f##*.}" in
      js|mjs)   FENCE='js'   ;;
      jsx)      FENCE='jsx'  ;;
      json)     FENCE='json' ;;
      md)       FENCE=''     ;;
      css)      FENCE='css'  ;;
      html|xsl) FENCE='html' ;;
      sh)       FENCE='bash' ;;
      py)       FENCE='python' ;;
      yml|yaml) FENCE='yaml' ;;
      *)        FENCE=''     ;;
    esac
    echo '```'"${FENCE}"
    cat "$f"
    # ensure code fence on its own line even if file lacks trailing newline
    echo ''
    echo '```'
  done < <(git ls-files \
            | grep -v -E "${SKIP_EXT_REGEX}" \
            | grep -v -E "${SKIP_FILE_REGEX}" \
            | sort)

  echo
  echo '---'
  echo
  echo "## END OF BUNDLE"
  echo
  echo "Files included: see Table of Contents above."
  echo "Generated by scripts/build-bundle.sh."
} > "${OUT}"

# Copy to common upload locations
cp "${OUT}" "${HOME}/Downloads/perplexity-bundle.md"
cp "${OUT}" "${HOME}/Desktop/perplexity-bundle.md"

# Report
LINES=$(wc -l < "${OUT}" | tr -d ' ')
SIZE=$(du -h "${OUT}" | awk '{print $1}')
FILES_IN=$(git ls-files | grep -v -E "${SKIP_EXT_REGEX}" | grep -v -E "${SKIP_FILE_REGEX}" | wc -l | tr -d ' ')

echo "Bundle generated: ${OUT}"
echo "  Dashboard version: ${VERSION}"
echo "  Files included:    ${FILES_IN}"
echo "  Lines:             ${LINES}"
echo "  Size:              ${SIZE}"
echo "  Git ref:           ${GIT_REF}${GIT_DIRTY}"
echo ""
echo "Copies:"
echo "  ${HOME}/Downloads/perplexity-bundle.md"
echo "  ${HOME}/Desktop/perplexity-bundle.md"
echo ""
echo "Verify all three identical:"
md5 -q "${OUT}" "${HOME}/Downloads/perplexity-bundle.md" "${HOME}/Desktop/perplexity-bundle.md"
